## Ansible playbook to install shadowsocks-libev on a Debian-based system

- name: Install shadowsocks-libev
  become: yes
  
  # ============================================================================
  vars:
    host_group: localhost
    # Your 'hosts', can be a group or a single host, e.g. 'localhost' if
    # you want to run the playbook on the local machine.

    ss_password: PASSWORD_HERE
    # Will be used to connect to the shadowsocks server.

    ss_method: aes-256-gcm
    # Shadowsocks encrypt method: rc4-md5,
    # aes-128-gcm, aes-192-gcm, aes-256-gcm,
    # aes-128-cfb, aes-192-cfb, aes-256-cfb,
    # aes-128-ctr, aes-192-ctr, aes-256-ctr,
    # camellia-128-cfb, camellia-192-cfb,
    # camellia-256-cfb, bf-cfb,
    # chacha20-ietf-poly1305,
    # xchacha20-ietf-poly1305,
    # salsa20, chacha20 and chacha20-ietf.
    # The default cipher is chacha20-ietf-poly1305.

    python3_venv_path: /usr/bin/python3-venv
    # Virtual environment for Python3. Just leave it as is.

    ss_port: '8388'
  # ============================================================================

  hosts: "{{ host_group }}"
  tasks:

    - name: Update system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure Docker is installed
      become: yes
      apt:
        name: docker.io
        state: present
        
    - name: Start Docker
      become: yes
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure python3 is installed
      become: yes
      apt:
        name: python3
        state: present

    - name: Ensure pip3 is installed
      become: yes
      apt:
        name: python3-pip
        state: present

    - name: Create a virtual environment and install Docker Python library
      become: yes
      block:
        - name: Ensure python3-venv is installed
          apt:
            name: python3-venv
            state: present
    
        - name: Create a virtual environment
          command: python3 -m venv {{ python3_venv_path }}
          args:
            creates: "{{ python3_venv_path }}"
    
        - name: Install Docker Python library in the virtual environment
          command: "{{ python3_venv_path }}/bin/pip install docker"

    - name: Install shadowsocks
      command: docker pull shadowsocks/shadowsocks-libev

    - name: Deploy shadowsocks
      become: yes
      vars:
        ansible_python_interpreter: "{{ python3_venv_path }}/bin/python3"
      docker_container:
        name: shadowsocks
        image: shadowsocks/shadowsocks-libev
        ports:
          - "{{ ss_port }}:8388"
          - "{{ ss_port }}:8388/udp"
        env:
          PASSWORD: "{{ ss_password }}"
          METHOD: "{{ ss_method }}"
        state: started
        restart_policy: always
        container_default_behavior: no_defaults

    - name: Clear apt cache
      apt:
        autoclean: yes

    - name: Print data to access shadowsocks-libev
      debug:
        msg: "To access shadowsocks, use the following data: IP: {{ ansible_host }}, Port: {{ ss_port }}, Method: {{ ss_method }}"
